### ISSUE TITLE
TEST_CASE variable is not being picked up by `make test`

### ISSUE THREAD

**Issue by TomasTomecek** [sclorg/postgresql-container#178]
seems like build.sh should pass the list of selected test cases to `test/run`

**Comment by pkubatrh** [comment]
You are right, it is no longer picked up after we made the move to common container building/testing scripts (over at https://github.com/sclorg/container-common-scripts) and it is there that the TEST_CASE variable should be reintroduced, since the postgresql test suite should already be prepared for it.

**Comment by pkubatrh** [comment]
Similar variable reintroduced in https://github.com/sclorg/postgresql-container/pull/231

Will modify the docs accordingly
