### ISSUE TITLE
How we will enable the ssl on this setup ?

### ISSUE THREAD

**Issue by haridas** [sclorg/postgresql-container#181]
We were using this, but finding it difficult to enable `ssl=on`, and injecting the crt and key files in `postgres` user permissions.

See the stackoverflow entry i created for this, for more details: -https://stackoverflow.com/questions/45353038/how-to-mount-secret-in-openshift-with-uidgid-set-correctly

**Comment by pkubatrh** [comment]
Sorry for the late response. I see you already got a response on the stack overflow entry so this might not be as useful to you anymore, but just wanted to add that there is now an [example](https://github.com/sclorg/postgresql-container/tree/master/examples/enable-ssl) for enabling ssl using s2i added in https://github.com/sclorg/postgresql-container/pull/342

Closing for now as I think the issue is resolved, but feel free to re-open if you run into some more problems.
