### ISSUE TITLE
In the case when "/var/lib/pgsql/data" is mountpoint

### ISSUE THREAD

**Issue by tzkoba** [sclorg/postgresql-container#299]
I'd like to build postgresql-container(centos/postgresql-10-centos7) with rook(https://github.com/rook/rook).

Before deploying postgresql-container, I built an environment of rook.

And then, I tried to deploy postgresql-container with rook(Ceph RBD) as persistent volume.
But errors shown hereunder occured  in its pod.(from kubectl logs)

"mkdir: cannot create directory '/var/lib/pgsql/data/userdata': Permission denied"

I guess because "/var/lib/pgsql/data" is mountpoint.

Can I use persisitent volume excluding local node path with postgresql-container?
How can I grant a privilege for "'/var/lib/pgsql/data"?

**Comment by praiskup** [comment]
> Can I use persisitent volume excluding local node path with
> postgresql-container?

I am not familiar with Rook environment, so I'm not sure what happens with
`/var/lib/pgsql/data` mount point.  The thing is that the PID 1 process in
container needs to be run by PID/GID which _is_ able to write there (btw. our
scripting shouldn't really mind whether it is or is not a mount point).

In OpenShift each container is run deliberately under different UID (there's
used random not-yet used UID).  If you don't do this (and you keep the default
UID/GID image setup) -- it should be enough to follow
[the instructions](https://github.com/sclorg/postgresql-container/tree/generated/10#environment-variables-and-volumes). See the *Notice: When mounting [...]* part.

I'm closing this since this sounds like question-only, but feel free to comment more.

**Comment by tzkoba** [comment]
Thanks praiskup, I got it.
As you mentioned, whether "/var/lib/pgdata" was a mountpoint  wasn't the cause.

After I modified my settings following your link , centos/postgresql-10-centos7 ran well.

Because Rook is based on Ceph, It was hard to find their mountpoint.
But I can find below.

`[centos@ip-hoge]$ sudo df -h|grep rbd`
`/dev/rbd0       4.9G  1.2G  3.5G  26% /var/lib/kubelet/plugins/ceph.rook.io/rook-ceph-system/mounts/pvc-feed3e1d-xxx`

And I executed setfacl commands to their directory, that's all.

I understand these settings are necessary to all nodes running centos/postgresql-10-centos7.

So it may not be a better way.
