### ISSUE TITLE
Configure postgres 

### ISSUE THREAD

**Issue by johannesluedke** [sclorg/postgresql-container#307]
I would like to change some postgres parameters (`wal_level`, `archive_mode`, `archive_timeout`) in a Dockerfile that inherits `FROM centos/postgresql-10-centos7` 

What is the recommended way of doing this?

**Comment by praiskup** [comment]
I'd suggest you to use s2i instead of re-building your own image (you don't have to take care of image updates later). https://github.com/sclorg/postgresql-container/tree/generated/10#extending-image

The scripting at runtime takes all the `/opt/app-root/src/postgresql-cfg/*.conf` files and includes them into postgresql.conf, so you can create such config files manually (but htat is not  supported nor documented, the location might change).
