### ISSUE TITLE
run_change_password_test() does not test password change

### ISSUE THREAD

**Issue by zmiklank** [sclorg/postgresql-container#542]

**Comment by hhorak** [comment]
The attempt to fix the SELinux issues #538 added creation of a new volume, that would make the test invalid, because the new container would work with empty/new data, which would not test changing password itself. However, the newly created volume directory was not used actually, so the test worked with previous data actually and likely did not fix the SELinux messages. In any case, #543 should fix this issue with SELinux messages reported originally as #536.
